#!/bin/bash
#!/bin/zsh
# ^- Must work in both

# ===============================================================
# shell_shared_desktop_flatpak
# Eskild Hustvedt
# ===============================================================
# This file contains aliases for flatpak, including aliases for using
# flatpak-versions of apps if installed

# Append flatpak to the path
if [ -e "$HOME/.local/share/flatpak/exports/bin" ]; then
    export PATH="$PATH:$HOME/.local/share/flatpak/exports/bin"
fi
if [ -e /var/lib/flatpak/exports/bin ]; then
    export PATH="$PATH:/var/lib/flatpak/exports/bin"
fi

# Use flatpak as a user
alias flatpak="flatpak --user"

# Initialize flatpak with flathub
alias flatpak-init-flathub="flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"

function aliasIfMissing ()
{
    app="$1";shift
    if ! type $app &>/dev/null; then
        alias "$app"="$@"
    fi
}

if [ -e ~/.local/share/flatpak ]; then
    aliasIfMissing gitg org.gnome.gitg
    aliasIfMissing lowriter "org.libreoffice.LibreOffice --writer"
    aliasIfMissing localc "org.libreoffice.LibreOffice --calc"
    aliasIfMissing loimpress "org.libreoffice.LibreOffice --impress"
    aliasIfMissing lobase "org.libreoffice.LibreOffice --base"
fi
